"""The data contract. Imports nothing from the rest of the codebase.

Import our envelope as `from policycheck.contracts import Field` — it shadows
`pydantic.Field`, so in files needing both, alias pydantic's as `PydanticField`.
"""

from policycheck.contracts.enums import (
    AggregateBasis,
    AIBasis,
    AIScope,
    AuditBasis,
    BusinessIncomeBasis,
    CausesOfLoss,
    Confidence,
    CoverageTrigger,
    DeductibleBasis,
    PageClassification,
    ValuationBasis,
    ValueBasis,
)
from policycheck.contracts.field import (
    INCLUDED,
    BBox,
    Field,
    IncludedSentinel,
    Money,
    agreement,
)
from policycheck.contracts.finding import (
    SECTION_ORDER,
    TOOL_FINDINGS,
    ComparisonResult,
    Finding,
    FindingSide,
    FindingType,
    NarrationInput,
    NarrationSide,
    Scalar,
    Section,
    Severity,
    Unit,
)
from policycheck.contracts.manifest import DecoyChange, InjectedChange, Manifest
from policycheck.contracts.snapshot import (
    AdditionalInsured,
    Address,
    DocumentMeta,
    Exclusion,
    FormRef,
    GeneralLiability,
    Identity,
    PolicySnapshot,
    Premium,
    PrimaryNoncontributory,
    Property,
    PropertyLocation,
    RiskTransfer,
    Unresolved,
    WaiverOfSubrogation,
)

__all__ = [
    "INCLUDED",
    "SECTION_ORDER",
    "TOOL_FINDINGS",
    "AIBasis",
    "AIScope",
    "AdditionalInsured",
    "Address",
    "AggregateBasis",
    "AuditBasis",
    "BBox",
    "BusinessIncomeBasis",
    "CausesOfLoss",
    "ComparisonResult",
    "Confidence",
    "CoverageTrigger",
    "DecoyChange",
    "DeductibleBasis",
    "DocumentMeta",
    "Exclusion",
    "Field",
    "Finding",
    "FindingSide",
    "FindingType",
    "FormRef",
    "GeneralLiability",
    "Identity",
    "IncludedSentinel",
    "InjectedChange",
    "Manifest",
    "Money",
    "NarrationInput",
    "NarrationSide",
    "PageClassification",
    "PolicySnapshot",
    "Premium",
    "PrimaryNoncontributory",
    "Property",
    "PropertyLocation",
    "RiskTransfer",
    "Scalar",
    "Section",
    "Severity",
    "Unit",
    "Unresolved",
    "ValuationBasis",
    "ValueBasis",
    "WaiverOfSubrogation",
    "agreement",
]
